### PR TITLE
DOC: Update outdated info on the about window

### LINKED ISSUE #154: Update About window
Current window has outdated links and copyright information

image

### PR DESCRIPTION
**Pull request by NicerNewerCar**
* Updates the `about window` with more up-to-date information
* Closes #154 

| Before | After |
| --- | --- |
| image | image |

### CODE REVIEW

**Comment by NicerNewerCar** [comment]
@jcfr Should the copyright line be `Copyright (c) 2011-2023, Brown University and Kitware, Inc.`, `Copyright (c) 2023, Brown University and Kitware, Inc.`, or something else entirely?

**Comment by jcfr** [comment]
I suggest the following:
* Clear the content in the ui file
* Update `AboutAutoscoper` constructor adding code like this:

   ```
   QTextBrowser* textBrowser = about->textBrowser_title;
   textBrowser->setFontPointSize(25);
   textBrowser->append("Autoscoper");
   textBrowser->setFontPointSize(11);
   textBrowser->append("");
   textBrowser->append(QString("v%1.%s").arg(2, 8));
   textBrowser->append("");
   textBrowser->insertHtml(QString(
    "<table align=\"center\" border=\"0\" width=\"80%\"><tr>"
    "<td align=\"center\"><a href=\"https://autoscoper.readthedocs.io/en/latest/about.html#license\">Licensing Information</a></td>"
    "<td align=\"center\"><a href=\"https://autoscoper.readthedocs.io/\">Website</a></td>"
    "</tr></table>"));
   ```

Notes:
* For now, let's hard-code the autoscoper version using `2` and `8`

Adapted from:
* https://github.com/Slicer/Slicer/blob/main/Base/QTCore/qSlicerCoreApplication.cxx#L1778
* https://github.com/Slicer/Slicer/blob/main/Base/QTApp/qSlicerAboutDialog.cxx#L44

**Comment by jcfr** [comment]
Thanks. Could you include before/after like in the previous comment ? 🙏

**Comment by jcfr** [comment]
| Before | After |
| --- | --- |
| image | image |

**Review by jcfr — APPROVED** [review]

**Pull request merged**
