### PR TITLE
Improve socket connection support

### PR DESCRIPTION
**Pull request by NicerNewerCar**
* Add flags to specify tracking data file organization
* Add installable python module PyAutoscoper
* Tweaks to socket.cpp
* Needs PR #55 to be merged before this PR is merged

### CODE REVIEW

**Review by amymmorton — APPROVED** [review]

**Review by jcfr — CHANGES_REQUESTED** [review]
Thanks @NicerNewerCar :100:

Few comments:
- [x] instead of `client_connection_libs/(matlab|PyAutoscoper)`, I suggest `Scripts/(matlab|python)`
- [x] relocation of `matlab` code should be done in a dedicated pull -request (https://github.com/BrownBiomechanics/Autoscoper/pull/55 could be rebased if not integrated beforehand)
- python
  - [x] python package should use `pyproject.toml` instead of `setup.py`. See [here](https://github.com/BICCN/cell-locator/tree/master/Scripts) for an example where a cli tool is tagged and managed along side a desktop application.
  - [x] python code should locally be linted through black
  - Optional:
    - [x] python linting should be added through GitHub Action
    - [ ] corresponding workflow for publishing on PyPI should be added. See [here](https://github.com/BICCN/cell-locator/blob/master/.github/workflows/python-publish.yml) for an example

**Comment by NicerNewerCar** [comment]
@jcfr Do you know who would have permission to create a secret for the PyPi api key?

**Comment by jcfr** [comment]
Once you the token is created within your pypi account, it can be added as a GitHub actions secret.

**Comment by NicerNewerCar** [comment]
@jcfr Sorry, I meant in this repository, according to the github docs you need to have admin rights in the repo to add a new secret and I do not have that.

**Comment by NicerNewerCar** [comment]
Also, when do we want the PyPI pipeline to run?

**Comment by jcfr** [comment]
> re: token

Once you share the token with me through a private channel (e.g google chat) creating a link using `https://onetimesecret.com/`, I will be able to add it as a repository secret called `PYPI_API_TOKEN`

> when do we want the PyPI pipeline to run?

Once a tag named `<prefix>-<version>` is created[^1]. `<prefix>` could be `cli` (or `client`). I was thinking we could have `python-cli` and `matlal-cli` ... we could still revisit later.

@allemangD and I discussed similar issue in the context of `Cell Locator`, and we settled on having two set of tags [^2]. One for the desktop app&library and one for the associated python tool.

We will address the tagging (and retroactive tagging) of Autoscoper later. For reference, the autoscoper version is currently hard-coded in `AutoscoperMainWindow.cpp` [^3]


[^1]: https://github.com/BICCN/cell-locator/blob/53689aa22fbdb33a339536556f62e13242210e1a/.github/workflows/python-publish.yml#L11-L14
[^2]: https://github.com/BICCN/cell-locator/pull/215#issuecomment-1322322065
[^3]: https://github.com/BrownBiomechanics/Autoscoper/blob/8010d3c09a0eb76e338e912a457aadd026227c5c/autoscoper/src/ui/AutoscoperMainWindow.cpp#L103

**Comment by jcfr** [comment]
> re: token
The project settings have been added and there is now repository secret called `PYPI_API_TOKEN`

**Comment by allemangD** [comment]
Using tag prefixes with `setuptools_scm` it is important to filter the tags used for version inference; for example if the git history shows tags in the order:

- `v2.0.0`
- `cli-v1.0.0`
- `v2.1.0`

The `setuptools_scm` would wrongly infer version `2.1.0`

See how I resolved this with a custom `git_describe_command` for cell-locator.

https://github.com/BICCN/cell-locator/blob/main/cell-locator-cli/pyproject.toml#L36-L46

**Comment by NicerNewerCar** [comment]
@jcfr I think this is pretty much sorted now. We just need to add a tag with the format `python-client-v*` to get the PyAutoscoper package onto PyPi for the soft launch of SA^M.

**Pull request merged**
