### PR TITLE
BUG: Fix incorrect application of input heuristics

### LINKED ISSUE #269: Optimization failing in new update
Software: Stable Release 5.6.1
Slicer Autoscoper Version: e1faa27 (2023-03-09)
Data: JOVE dataset -https://www.jove.com/t/63535/biplanar-videoradiography-dataset-for-model-based-pose-estimation
[SOLH001A.zip](https://github.com/BrownBiomechanics/Autoscoper/files/14563587/SOLH001A.zip)

The issue arises with the optimized tracking.

In the previous version of AS (version: 619546b, 2024-01-01), here is how the tracking appeared after all frames were optimized:
https://github.com/BrownBiomechanics/Autoscoper/assets/93012111/cbb3613b-c09d-4721-b5f8-e27a516397a4

And here's how the tracking appears in the current version (version: e1faa27, 2023-03-09) after optimizing all frames:

https://github.com/BrownBiomechanics/Autoscoper/assets/93012111/0ba78419-ca4a-4590-8421-cbe565fe5304

The same dataset and parameters were used for both videos. For both videos, the perturbed Tracking folder was loaded into Autoscoper (everything set to default except rows -> column). The filtersettingsSOL_Q.vie file was loaded, then the tracking dialog was executed with these settings:
image

### PR DESCRIPTION
**Pull request by NicerNewerCar**
Closes #269

### CODE REVIEW

**Review by amymmorton — COMMENTED** [review]
Not entirely clear on the error here- I saw the video of tracked ankle results - crazy flips- but I don't know what the pre tracked looked like? ... not certain I know what to test

**Comment by NicerNewerCar** [comment]
> Not entirely clear on the error here- I saw the video of tracked ankle results - crazy flips- but I don't know what the pre tracked looked like? ... not certain I know what to test

Open the current main branch and load in a fully tracked structure (preferably one with a wide range of motion) and track over those results. Then compare with this branch.

**Review by amymmorton — APPROVED** [review]
Optimizing w this branch looks good. I believe this also fixes my crash issue.

**Comment by jcfr** [comment]
Reviewing 4d2eec3, we can indeed observe that the term `- dFrame` was inadvertently introduced. 


image

Related pull requests:
* #255

**Review by jcfr — APPROVED** [review]

**Pull request merged**
