### PR TITLE
Fix open trial regression

### PR DESCRIPTION
**Pull request by jcfr**
This change is done anticipating the introduction of relative path support.

This pull request was created from work originally done by @NicerNewerCar in:
* https://github.com/BrownBiomechanics/Autoscoper/pull/142

Autoload tracking data was not using expected bone name:

* When auto loading tracking data on config load, the expected bone name was not being used.
* Updated to use the full name as shown in the UI/files

| | |
|--|--|
| Before | `.\Tracking\{trial name}_bone.tra` |
| After  |`.\Tracking\{trial_name}_bone_full_name.tra` |

Regression introduced in commit https://github.com/BrownBiomechanics/Autoscoper/commit/184bb70096d9a77c6b7a967855b2c8709d931d7d

### CODE REVIEW

**Comment by jcfr** [comment]
@NicerNewerCar In the commit message, you mentioned `_full_name`. Given the implementation of `VolumeDockWidget::getVolumeName`, I am assuming you meant `_dcm_cropped` ?

**Comment by jcfr** [comment]
I suggest to simply remove `getFullVolumeName` and fix the implementation of `getVolumeName`

**Comment by jcfr** [comment]
Suggested commit message when `Squash and merge` will be done:

```
BUG: Fix loading of tracking data as part of a trial.

When loading a trial configuration (e.g `/path/to/<trial_name>.cfg`), the file path to
the tracking data (`*.tra`) file is composed using this rule:

  <tracking_path_root>/<default_tracking_folder>/<trial_name>_<volume_name>.tra

where:
* `<tracking_path_root>` corresponds to the path where `<trial_name>.cfg` is located
* `<default_tracking_folder>` is `Tracking`
* `<task>` corresponds to the trial config filename without the extension (`<task>`)
* `<volume_name>` corresponds to the model file name without the extension 

This reverts logic integrated in 184bb7009 that was stripping the `_dcm_cropped` suffix from the volume name.

* Before: `.\Tracking\<trial_name>_bone.tra`
* After: `.\Tracking\<trial_name>_bone_dcm_cropped.tra`
```

**Comment by jcfr** [comment]
> * Updated to use the full name as shown in the UI/files

@NicerNewerCar When you have a chance, could you share a screenshot ?

**Comment by NicerNewerCar** [comment]
> @NicerNewerCar In the commit message, you mentioned `_full_name`. Given the implementation of `VolumeDockWidget::getVolumeName`, I am assuming you meant `_dcm_cropped` ?

That is correct.

> @NicerNewerCar When you have a chance, could you share a screenshot ?

image

**Comment by jcfr** [comment]
Attempting to reproduce the issue, I downloaded the `WN00113.zip` from the shared Google drive  (`SlicerAutoscoperM / sampleData_internal / WN00113.zip`).

After extracting it to `/home/jcfr/Data/Autoscoper_SampleData_internal/WN00113`, I modified the file `WN00113/Autoscoper/flx_ext.cfg` by doing the following replacement:
* `P:\iTWA_Instrumented_Total_Wrist\Subjects\NORMAL\WN00113` -> `/home/jcfr/Data/Autoscoper_SampleData_internal/WN00113`
* `\` -> `/`

<details><summary>Click to see diff of changes applied to `flx_ext.cfg`</summary>

```diff
1,5c1,5
< mayaCam_csv P:\iTWA_Instrumented_Total_Wrist\Subjects\NORMAL\WN00113\Data_XROMM\Calibration_MayaCam\xr_pre_cube_4_cam01_MayaCam.txt
< mayaCam_csv P:\iTWA_Instrumented_Total_Wrist\Subjects\NORMAL\WN00113\Data_XROMM\Calibration_MayaCam\xr_pre_cube_4_cam02_MayaCam.txt
< CameraRootDir P:\iTWA_Instrumented_Total_Wrist\Subjects\NORMAL\WN00113\Data_XROMM\XMA_UND\xr_flx_ext_cam01UND
< CameraRootDir P:\iTWA_Instrumented_Total_Wrist\Subjects\NORMAL\WN00113\Data_XROMM\XMA_UND\xr_flx_ext_cam02UND
< VolumeFile P:\iTWA_Instrumented_Total_Wrist\Subjects\NORMAL\WN00113\Models\mc2_mc3\mc2_mc3_dcm_cropped.tif
---
> mayaCam_csv /home/jcfr/Data/Autoscoper_SampleData_internal/WN00113/Data_XROMM/Calibration_MayaCam/xr_pre_cube_4_cam01_MayaCam.txt
> mayaCam_csv /home/jcfr/Data/Autoscoper_SampleData_internal/WN00113/Data_XROMM/Calibration_MayaCam/xr_pre_cube_4_cam02_MayaCam.txt
> CameraRootDir /home/jcfr/Data/Autoscoper_SampleData_internal/WN00113/Data_XROMM/XMA_UND/xr_flx_ext_cam01UND
> CameraRootDir /home/jcfr/Data/Autoscoper_SampleData_internal/WN00113/Data_XROMM/XMA_UND/xr_flx_ext_cam02UND
> VolumeFile /home/jcfr/Data/Autoscoper_SampleData_internal/WN00113/Models/mc2_mc3/mc2_mc3_dcm_cropped.tif
8c8
< VolumeFile P:\iTWA_Instrumented_Total_Wrist\Subjects\NORMAL\WN00113\Models\rad\rad_dcm_cropped.tif
---
> VolumeFile /home/jcfr/Data/Autoscoper_SampleData_internal/WN00113/Models/rad/rad_dcm_cropped.tif
11c11
< VolumeFile P:\iTWA_Instrumented_Total_Wrist\Subjects\NORMAL\WN00113\Models\mc3\mc3_dcm_cropped.tif
---
> VolumeFile /home/jcfr/Data/Autoscoper_SampleData_internal/WN00113/Models/mc3/mc3_dcm_cropped.tif
14c14
< VolumeFile P:\iTWA_Instrumented_Total_Wrist\Subjects\NORMAL\WN00113\Models\uln\uln_dcm_cropped.tif
---
> VolumeFile /home/jcfr/Data/Autoscoper_SampleData_internal/WN00113/Models/uln/uln_dcm_cropped.tif

```

</details>

After building Autoscoper based of this branch, I tried to load the file `/home/jcfr/Data/Autoscoper_SampleData_internal/WN00113/Models/mc2_mc3/mc2_mc3_dcm_cropped.tif` (using either `PyAutoscoper` or the `UI`) and it failed with the following:

```
Trial configuration file is missing the `Version` key. Assuming version is 1.0
See /home/jcfr/Data/Autoscoper_SampleData_internal/WN00113/Autoscoper/flx_ext-ok.cfg.

Please check the trial configuration specification.
See https://autoscoper.readthedocs.io/en/latest/file-specifications/config.htmlReading MayaCam 2.0 file: /home/jcfr/Data/Autoscoper_SampleData_internal/WN00113/Data_XROMM/Calibration_MayaCam/xr_pre_cube_4_cam01_MayaCam.txt
Reading MayaCam 2.0 file: /home/jcfr/Data/Autoscoper_SampleData_internal/WN00113/Data_XROMM/Calibration_MayaCam/xr_pre_cube_4_cam02_MayaCam.txt
TIFFOpen: /home/jcfr/Data/Autoscoper_SampleData_internal/WN00113/Models/mc2_mc3/mc2_mc3_dcm_cropped.tif: No such file or directory.
Unable to open volume file: /home/jcfr/Data/Autoscoper_SampleData_internal/WN00113/Models/mc2_mc3/mc2_mc3_dcm_cropped.tif
```

**Comment by jcfr** [comment]
Same observation with `WN00113/Autoscoper/rad_uln.cfg`, the following error is reported:

```
Trial configuration file is missing the `Version` key. Assuming version is 1.0
See /home/jcfr/Data/Autoscoper_SampleData_internal/WN00113/Autoscoper/rad_uln-ok.cfg.

Please check the trial configuration specification.
See https://autoscoper.readthedocs.io/en/latest/file-specifications/config.htmlReading MayaCam 2.0 file: /home/jcfr/Data/Autoscoper_SampleData_internal/WN00113/Data_XROMM/Calibration_MayaCam/xr_pre_cube_4_cam01_MayaCam.txt
Reading MayaCam 2.0 file: /home/jcfr/Data/Autoscoper_SampleData_internal/WN00113/Data_XROMM/Calibration_MayaCam/xr_pre_cube_4_cam02_MayaCam.txt
TIFFOpen: /home/jcfr/Data/Autoscoper_SampleData_internal/WN00113/Models/mc2_mc3/mc2_mc3_dcm_cropped.tif: No such file or directory.
Unable to open volume file: /home/jcfr/Data/Autoscoper_SampleData_internal/WN00113/Models/mc2_mc3/mc2_mc3_dcm_cropped.tif
```

i will know remove the `mc2_mc3/` references from the `.cfg` file and try again

**Comment by jcfr** [comment]
```diff
5,7c5,7
< VolumeFile /home/jcfr/Data/Autoscoper_SampleData_internal/WN00113/Models/mc2_mc3/mc2_mc3_dcm_cropped.tif
< VolumeFlip 0 0 0
< VoxelSize 0.390625 0.390625 0.625
---
> #VolumeFile /home/jcfr/Data/Autoscoper_SampleData_internal/WN00113/Models/mc2_mc3/mc2_mc3_dcm_cropped.tif
> #VolumeFlip 0 0 0
> #VoxelSize 0.390625 0.390625 0.625
14,16c14,16
< VolumeFile /home/jcfr/Data/Autoscoper_SampleData_internal/WN00113/Models/uln/uln_dcm_cropped.tif
< VolumeFlip 0 0 0
< VoxelSize 0.390625 0.390625 0.625
---
> #VolumeFile /home/jcfr/Data/Autoscoper_SampleData_internal/WN00113/Models/uln/uln_dcm_cropped.tif
> #VolumeFlip 0 0 0
> #VoxelSize 0.390625 0.390625 0.625
```

**Comment by jcfr** [comment]
The issue is that if the `.cfg` file is renamed, the loading of the tracking data will just fail.

Indeed, the heuristic is the following:

```
When loading a trial configuration (e.g `/path/to/<trial_name>.cfg`), the file path to
the tracking data (`*.tra`) file is composed using this rule:

  <tracking_path_root>/<default_tracking_folder>/<trial_name>_<volume_name>.tra

where:
* `<tracking_path_root>` corresponds to the path where `<trial_name>.cfg` is located
* `<default_tracking_folder>` is `Tracking`
* `<task>` corresponds to the trial config filename without the extension (`<task>`)
* `<volume_name>` corresponds to the model file name without the extension
```

**Comment by jcfr** [comment]
@NicerNewerCar When you have a chance, could you try to load the `.cfg` that is failing after building of `main` where the following pull request has been integrated, this should provide a more informative output:
*  https://github.com/BrownBiomechanics/Autoscoper/pull/184

**Review by NicerNewerCar — APPROVED** [review]
LGTM

New output:

```
Setting up a new trial...
Filename: C:/Users/anthony.lombardi/Projects/SAM/Data/WN00113/Autoscoper/flx_ext.cfg
Volume Name: C:\Users\anthony.lombardi\Projects\SAM\Data\WN00113\Models\rad\rad_dcm_cropped.tif
Volume Name: C:\Users\anthony.lombardi\Projects\SAM\Data\WN00113\Models\mc3\mc3_dcm_cropped.tif
Root Path is: C:/Users/anthony.lombardi/Projects/SAM/Data/WN00113/Autoscoper
Task Name: flx_ext
Tracking Data Directory: C:/Users/anthony.lombardi/Projects/SAM/Data/WN00113/Autoscoper/Tracking
Looking for Tracking Data File: flx_ext_rad_dcm_cropped.tra
  Not Found
Looking for Tracking Data File: flx_ext_mc3_dcm_cropped.tra
  Not Found
Current NCC is: 1.86627
```

**Comment by jcfr** [comment]
Without this patch, I am able to successfully load (*) the `flx_ext.cfg` found in  `Autoscoper_SampleData_internal/WN00113/Autoscoper`.

As you can see below, the tracking files are found because the `_dcm_cropped` suffix is effectively stripped.

This means we should **NOT** integrate this pull request.

```
Filename: /home/jcfr/Data/Autoscoper_SampleData_internal/WN00113/Autoscoper/flx_ext.cfg
Volume Name: /home/jcfr/Data/Autoscoper_SampleData_internal/WN00113/Models/rad/rad_dcm_cropped.tif
Volume Name: /home/jcfr/Data/Autoscoper_SampleData_internal/WN00113/Models/mc3/mc3_dcm_cropped.tif
Root Path is: /home/jcfr/Data/Autoscoper_SampleData_internal/WN00113/Autoscoper
Task Name: flx_ext
Tracking Data Directory: /home/jcfr/Data/Autoscoper_SampleData_internal/WN00113/Autoscoper/Tracking
Looking for Tracking Data File: flx_ext_rad.tra
Load Tracking Data Volume 0 : /home/jcfr/Data/Autoscoper_SampleData_internal/WN00113/Autoscoper/Tracking/flx_ext_rad.tra
 save as matrix   : 1
 save as rows     : 1
 save with commas : 1
 convert to cm    : 0
 convert to rad   : 0
 interpolate      : 0
Looking for Tracking Data File: flx_ext_mc3.tra
Load Tracking Data Volume 1 : /home/jcfr/Data/Autoscoper_SampleData_internal/WN00113/Autoscoper/Tracking/flx_ext_mc3.tra
 save as matrix   : 1
 save as rows     : 1
 save with commas : 1
 convert to cm    : 0
 convert to rad   : 0
 interpolate      : 0
Current NCC is: 1.00527

```


(*) This required to comment the line referencing `mc2_mc3` and `uln`

```diff
5,7c5,7
< VolumeFile /home/jcfr/Data/Autoscoper_SampleData_internal/WN00113\Models\mc2_mc3\mc2_mc3_dcm_cropped.tif
< VolumeFlip 0 0 0
< VoxelSize 0.390625 0.390625 0.625
---
> #VolumeFile /home/jcfr/Data/Autoscoper_SampleData_internal/WN00113\Models\mc2_mc3\mc2_mc3_dcm_cropped.tif
> #VolumeFlip 0 0 0
> #VoxelSize 0.390625 0.390625 0.625
14,16c14,16
< VolumeFile /home/jcfr/Data/Autoscoper_SampleData_internal/WN00113\Models\uln\uln_dcm_cropped.tif
< VolumeFlip 0 0 0
< VoxelSize 0.390625 0.390625 0.625
---
> #VolumeFile /home/jcfr/Data/Autoscoper_SampleData_internal/WN00113\Models\uln\uln_dcm_cropped.tif
> #VolumeFlip 0 0 0
> #VoxelSize 0.390625 0.390625 0.625

```

**Comment by jcfr** [comment]
Considering the last comment https://github.com/BrownBiomechanics/Autoscoper/pull/182#issuecomment-1672035301, I am closing this pull request.

@NicerNewerCar In case I missed something, we can revisit and further work on this.

**Pull request closed without merging**
