### PR TITLE
Pyautoscoper docs

### LINKED ISSUE #98: PyAutoscoper: Create relevant documentation
Utilize Sphinx to create documentation with examples and a class reference.

### PR DESCRIPTION
**Pull request by NicerNewerCar**
* Closes #98

### CODE REVIEW

**Comment by NicerNewerCar** [comment]
@kaitohl Here is some documentation I put together for PyAutoscoper. If you check out this PR locally, you can find instructions for building the documentation in the `./scripts/python` folder. Let me know what you think the docs need!

**Comment by kaitohl** [comment]
Documentation looks great!

**Comment by NicerNewerCar** [comment]
@jcfr Did we land on a line length of `88` or `120`? It looks like the pre-commit action is expecting `88`. https://github.com/BrownBiomechanics/Autoscoper/actions/runs/4632588128/jobs/8196829594?pr=112#step:4:98

**Comment by jcfr** [comment]
> re: line length

We indeed settled on 120. Changes similar to the following need to be added to Autoscoper as well:
* https://github.com/BrownBiomechanics/SlicerAutoscoperM/pull/21

**Comment by NicerNewerCar** [comment]
Looks like its set to `88` in the toml:
https://github.com/BrownBiomechanics/Autoscoper/blob/e6911e8f1a55e03b71321faf4938745e4a02bda3/scripts/python/pyproject.toml#L29-L32

I can Update that 120 and see if it solves the issue.
I will open another PR for this.

**Comment by jcfr** [comment]
> I will open another PR for this

* https://github.com/BrownBiomechanics/Autoscoper/pull/115

**Comment by jcfr** [comment]
Before moving forward with the integration, I think we should consider autoscoper documentation in its entirety.

I think having documentation for autoscoper including sub section for client may be easier to maintain. 

Similar to what we have done for `cell-locator][^1]

The corresponding documentation would be available as `autoscoper.readthedocs.io`

[^1]: https://cell-locator.readthedocs.io/en/latest/command-line-tools.html

**Comment by NicerNewerCar** [comment]
Closing this PR in favor of #117

**Pull request closed without merging**
