### PR TITLE
Remove deprecated policy usage

### LINKED ISSUE #18: COMP: Remove conflict with setting of CMAKE_CURRENT_SOURCE_DIR
Remove setting of CMAKE_CURRENT_SOURCE_DIR in [autoscoper/CMakeLists.txt](https://github.com/BrownBiomechanics/Autoscoper/blob/bcb51534663b70bd506a1699daec4f64502da7d5/autoscoper/CMakeLists.txt), this conflict with built-in [CMAKE_CURRENT_SOURCE_DIR](https://cmake.org/cmake/help/v3.24/variable/CMAKE_CURRENT_SOURCE_DIR.html) variable

### LINKED ISSUE #19: COMP: Remove setting policy CMP0020 to OLD

### PR DESCRIPTION
**Pull request by NicerNewerCar**
Removes usage of old CMP0020
closes #19

### CODE REVIEW

**Comment by NicerNewerCar** [comment]
wait for #9  to be merged in then rebase as needed

**Comment by jcfr** [comment]
Considering that requiring a specific version of CMale implies that old policies introduced beforehand are automatically set to `NEW`, there is no need to explicitly set this older policy to `NEW`.

Instead, review history of the project to understand why the policy was explicitly set to `OLD` and if the problem tentatively addressed by forcing this policy is not an issue, describe so in the commit message.

**Comment by NicerNewerCar** [comment]
It looks like the policy was only set to `OLD` when [Qt5](https://github.com/BrownBiomechanics/Autoscoper/commit/b948cb6b308154d062b4deba9d91b9cf577021f3) was added. There was no reason given for why It was explicitly set. 

I can update the commit to not force the policy to be `NEW`.

**Comment by jcfr** [comment]
Closing. This is superseded by https://github.com/BrownBiomechanics/Autoscoper/pull/9

**Pull request closed without merging**
