### PR TITLE
ENH: Add setting to switch between viewport logic

### PR DESCRIPTION
**Pull request by NicerNewerCar**
* See comment https://github.com/BrownBiomechanics/Autoscoper/issues/203#issuecomment-1768948851
* Adds a new option to toggle between the changes introduced in #204 and the previous code.
    * Defaults to off (ie. previous logic) 
* Adds new function to PyAutoscoper and the MATLAB class
    * `toggleViewportConversionMethod` takes a 0 or 1 for the old and new methods respectively.   
* image

### CODE REVIEW

**Comment by jcfr** [comment]
Before we integrate this one, could you create independent PRs for:
- only reverting how `render_height` and `render_width` are computed. This will allows @amymmorton to move forward with the agreement and performance tests.
- only adding the docstrings

**Comment by NicerNewerCar** [comment]
> Before we integrate this one, could you create independent PRs for:
> 
> * only reverting how `render_height` and `render_width` are computed. This will allows @amymmorton to move forward with the agreement and performance tests.
> * only adding the docstrings

See:
* #212 
* #213

**Comment by amymmorton** [comment]
I need to test the proposed alternate more .. a modified aspect ratio still doesn't sit right with me. Reverting back to pre 204 is a good move. - SLow down still not fully attributed to this issue

**Review by amymmorton — CHANGES_REQUESTED** [review]
See:

https://github.com/BrownBiomechanics/Autoscoper/issues/203#issuecomment-1773132603

**Comment by jcfr** [comment]
> Reverting back to pre 204 is a good move

For reference:

* https://github.com/BrownBiomechanics/Autoscoper/pull/212

**Comment by jcfr** [comment]
For convenience, I re-based against the latest `main` and removed the introduction of comment now integrated through https://github.com/BrownBiomechanics/Autoscoper/pull/213

**Pull request closed without merging**
